### ISSUE TITLE
Testing Milestone

### ISSUE THREAD

**Issue by ControlCplusControlV** [manifoldfinance/mevETH2#2]
Milestone to aggregate many different testing plans in place (should likely be migrated to the new repo when ready)
 
- [ ] manifoldfinance/mevETH2#3
- [x] manifoldfinance/mevETH2#1
- [ ] - t11's solcurity checklist
- [ ] - Set up End to end tests
- [ ] - Test OFT interactions with multi-chain
- [ ] manifoldfinance/mevETH2#4
- [x] - Goerli testnet deployment
